name: advent_of_coding
description: Advent of coding challenge
version: 1.0.0
repository: https://github.com/Safal-Shrestha-SS/Advent-of-Coding

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  dart_console: 4.1.1 

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
