// ignore_for_file: public_member_api_docs, sort_constructors_first
import 'package:advent_of_coding/file_reader.dart';
import 'package:dart_console/dart_console.dart';

// Scanning across the city, you find that there are actually many such antennas. Each antenna is tuned to a specific frequency indicated by a single lowercase letter, uppercase letter, or digit. You create a map (your puzzle input) of these antennas. For example:

// ............
// ........0...
// .....0......
// .......0....
// ....0.......
// ......A.....
// ............
// ............
// ........A...
// .........A..
// ............
// ............
// The signal only applies its nefarious effect at specific antinodes based on the resonant frequencies of the antennas. In particular, an antinode occurs at any point that is perfectly in line with two antennas of the same frequency - but only when one of the antennas is twice as far away as the other. This means that for any pair of antennas with the same frequency, there are two antinodes, one on either side of them.

// So, for these two antennas with frequency a, they create the two antinodes marked with #:

// ..........
// ...#......
// ..........
// ....a.....
// ..........
// .....a....
// ..........
// ......#...
// ..........
// ..........
// Adding a third antenna with the same frequency creates several more antinodes. It would ideally add four antinodes, but two are off the right side of the map, so instead it adds only two:

// ..........
// ...#......
// #.........
// ....a.....
// ........a.
// .....a....
// ..#.......
// ......#...
// ..........
// ..........
// Antennas with different frequencies don't create antinodes; A and a count as different frequencies. However, antinodes can occur at locations that contain antennas. In this diagram, the lone antenna with frequency capital A creates no antinodes but has a lowercase-a-frequency antinode at its location:

// ..........
// ...#......
// #.........
// ....a.....
// ........a.
// .....a....
// ..#.......
// ......A...
// ..........
// ..........
// The first example has antennas with two different frequencies, so the antinodes they create look like this, plus an antinode overlapping the topmost A-frequency antenna:

// ......#....#
// ...#....0...
// ....#0....#.
// ..#....0....
// ....0....#..
// .#....A.....
// ...#........
// #......#....
// ........A...
// .........A..
// ..........#.
// ..........#.
// Because the topmost A-frequency antenna overlaps with a 0-frequency antinode, there are 14 total unique locations that contain an antinode within the bounds of the map.

// Calculate the impact of the signal. How many unique locations within the bounds of the map contain an antinode?
void main() {
  var listOfString = readFile('lib/days/8/day_8_2.txt');
  List<List<String>> matrix = [];
  Map<String, List<Point>> uniqueMap = {};
  for (var i = 0; i < listOfString.length; i++) {
    matrix.add(listOfString[i].split(''));
    for (var j = 0; j < matrix[i].length; j++) {
      if (matrix[i][j] == '.') {
        continue;
      }
      if (uniqueMap.containsKey(matrix[i][j])) {
        uniqueMap[matrix[i][j]]?.add(Point(j, i));
      } else {
        uniqueMap[matrix[i][j]] = [Point(j, i)];
      }
    }
  }
  var horizontalLengeth = matrix[0].length;
  var verticalLength = matrix.length;
  Set<Point> uniquePoints = {};
  for (var i = 0; i < uniqueMap.length; i++) {
    var points = uniqueMap[uniqueMap.keys.elementAt(i)];
    for (var j = 0; j < points!.length; j++) {
      for (var k = 0; k < points.length; k++) {
        if (j == k) {
          continue;
        }
        var a = points[j];
        var b = points[k];
        var x = 0;
        var y = 0;
        var x1 = 0;
        var y1 = 0;
        x = a.x - b.x;
        y = a.y - b.y;
        x1 = a.x + x;
        y1 = a.y + y;
        if (x1 >= 0 &&
            x1 < horizontalLengeth &&
            y1 >= 0 &&
            y1 < verticalLength) {
          // print('x: $x1, y: $y1');
          uniquePoints.add(Point(x1, y1));
        }
      }
    }
  }
  print(uniquePoints.length);
}

class Point {
  int x;
  int y;
  Point(this.x, this.y);

  @override
  bool operator ==(covariant Point other) {
    if (identical(this, other)) return true;

    return other.x == x && other.y == y;
  }

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  String toString() => 'Point(x: $x, y: $y)';
}

void printMatrix(List<List<String>> matrix) {
  Console().clearScreen();
  for (var i = 0; i < matrix.length; i++) {
    print(matrix[i]);
  }
}
